"""Описание миграции

Revision ID: 2ca9da185055
Revises: fb6d05bf4638
Create Date: 2024-12-27 01:12:17.406702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca9da185055'
down_revision: Union[str, None] = 'fb6d05bf4638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movie_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'movie_url')
    # ### end Alembic commands ###
